# Generated by Django 4.2.7 on 2023-11-27 22:31

from django.db import migrations, models
import django.db.models.deletion
import pet_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, validators=[pet_app.validators.validate_name])),
                ('email_address', models.CharField(unique=True, validators=[pet_app.validators.validate_email])),
                ('age', models.IntegerField(default=18, validators=[pet_app.validators.validate_age])),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='pets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pet_app.owner'),
        ),
    ]
