# Generated by Django 4.2.7 on 2023-11-27 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0001_initial'),
        ('pet_app', '0003_rename_pets_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='owner_app.owner'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
