# Generated by Django 4.2.7 on 2023-11-27 23:12

from django.db import migrations, models
import owner_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, validators=[owner_app.validators.validate_name])),
                ('email_address', models.CharField(unique=True, validators=[owner_app.validators.validate_email])),
                ('age', models.IntegerField(default=18, validators=[owner_app.validators.validate_age])),
            ],
        ),
    ]
